export interface EkonsultaModel {
    ekonsultaId?: number;
    appointment_id?: string;
    user_id?: number;
    familySerialNo?: string;
    patientType?: boolean;
    NHTSNo?: string;
    maidenLastname?: string;
    maidenMiddleName?: string;
    mothersName?: string;
    mothersBirthday?: string;
    ethnicity?: string;
    purok?: string;
    zipCode?: string;
    NHTSClass?: boolean;
    PHICNo?: string;
    PHICClass?: boolean;
    bodyLength?: string;
    headCircumference?: string;
    skinfoldThickness?: string;
    weight?: string;
    BMI?: string;
    waistCircumference?: string;
    midUpperArmCircumference?: string;
    BP?: string;
    RR?: string;
    HR?: string;
    PR?: string;
    Temp?: string;
    chiefComplaints?: string;
    hospitalization?: boolean;
    asthma?: boolean;
    cancer?: boolean;
    cancerSpecify?: string;
    cerebrovascular?: boolean;
    coronary?: boolean;
    diabetes?: boolean;
    minorsurgeries?: boolean;
    emphysema?: boolean;
    epilepsy?: boolean;
    hepatitis?: boolean;
    hepatitisSpecify?: string;
    hyperlipidemia?: boolean;
    hypertension?: boolean;
    pepticUlcer?: boolean;
    COPD?: boolean;
    pneumonia?: boolean;
    thyroid?: boolean;
    UTI?: boolean;
    TB?: boolean;
    TBSpecify?: string;
    ifPTB?: boolean;
    ifPTBSpecify?: string;
    allergySpecify?: string;
    allergyDrugs?: string;
    Disability?: string;
    Drug?: string;
    Handicap?: string;
    Impairment?: string;
    Others?: boolean;
    operation1?: string;
    liverDisease?: boolean;
    operationDate1?: string;
    operation2?: string;
    operationDate2?: string;
    visualAcuity?: string;
    basicHearingTest?: string;
    newbornHearingTest?: string;
    cervicalCancerScreeningDone?: boolean;
    prostateCancerScreeningDone?: boolean;
    hivAidsScreeningDone?: boolean;
    developmentalAndMentalEvaluation?: string;
    expandedNewbornScreening?: boolean;
    CBC2?: boolean;
    bloodType?: boolean;
    bloodTypeSpecify?: string;
    FBS?: boolean;
    sputumMicroscopy?: boolean;
    slitSkinSmear?: boolean;
    totalCholesterol?: boolean;
    hdlCholesterol?: boolean;
    serumandBun?: boolean;
    routineUrinalysis?: boolean;
    katoKatz?: boolean;
    rapidPlasma?: boolean;
    igmAndIgG?: boolean;
    nonStructure?: boolean;
    hepaB?: boolean;
    fecalysis?: boolean;
    malarialSmear?: boolean;
    nucleicAndAmplification?: boolean;
    allergy?: boolean;
    smoking?: string;
    number_of_sticks?: number;
    alcohol?: string;
    number_of_bottles?: number;
    illicit_drugs?: string;
    no_of_packs?: string;
    skinPallor?: boolean;
    skinRashes?: boolean;
    allergyDrugsBl?: boolean;
    DisabilityBl?: boolean;
    DrugBl?: boolean;
    HandicapBl?: boolean;
    ImpairmentBl?: boolean;
    skinJaundice?: boolean;
    skinGoodSkinTurgor?: boolean;
    heentAnicteric?: boolean;
    heentIntactTympanic?: boolean;
    heentExudates?: boolean;
    heentPupils?: boolean;
    heentTonsil?: boolean;
    heentAuralDischarge?: boolean;
    heentNasalDischarge?: boolean;
    heentPalpableMass?: boolean;
    chestSymmetrical?: boolean;
    chestClearBreath?: boolean;
    chestRetractions?: boolean;
    chestCrackles?: boolean;
    chestWheeze?: boolean;
    heartAdynamic?: boolean;
    heartMurmurs?: boolean;
    heartNormalRate?: boolean;
    heartHeaves?: boolean;
    abdomenFlat?: boolean;
    abdomenGlobular?: boolean;
    abdomenFlabby?: boolean;
    abdomenMuscleGuarding?: boolean;
    abdomenTenderness?: boolean;
    abdomenPalpableMass?: boolean;
    extremetiesGrossDeformity?: boolean;
    extremetiesNormalGait?: boolean;
    extremetiesFullEqualPulse?: boolean;
    neurologicalNormal?: boolean;
    neurologicalDevelopmental?: boolean;
    neurologicalSeizures?: boolean;
    neurologicalMotorDeficit?: boolean;
    neurologicalSensoryDeficit?: boolean;
    diagnosis?: string;
    treatment?: string;
    healthcareProvider?: string;
    administeredBy?: string;
}

export const initialEkonsultaModel = (): EkonsultaModel => ({
    ekonsultaId: 0,
    appointment_id: "",
    user_id: 0,
    patientType: false,
    maidenLastname: "",
    maidenMiddleName: "",
    familySerialNo: "",
    mothersName: "",
    mothersBirthday: "",
    ethnicity: "",
    purok: "",
    zipCode: "",
    NHTSNo: "",
    NHTSClass: false,
    PHICNo: "",
    PHICClass: false,
    bodyLength: "",
    liverDisease: false,
    newbornHearingTest: "",
    headCircumference: "",
    skinfoldThickness: "",
    weight: "",
    BMI: "",
    waistCircumference: "",
    midUpperArmCircumference: "",
    BP: "",
    RR: "",
    HR: "",
    PR: "",
    Temp: "",
    chiefComplaints: "",
    hospitalization: false,
    asthma: false,
    cancer: false,
    cancerSpecify: "",
    cerebrovascular: false,
    coronary: false,
    diabetes: false,
    minorsurgeries: false,
    emphysema: false,
    epilepsy: false,
    hepatitis: false,
    hepatitisSpecify: "",
    hyperlipidemia: false,
    hypertension: false,
    pepticUlcer: false,
    COPD: false,
    pneumonia: false,
    thyroid: false,
    UTI: false,
    TB: false,
    TBSpecify: "",
    ifPTB: false,
    ifPTBSpecify: "",
    Others: false,
    operation1: "",
    allergySpecify: "",
    allergyDrugs: "",
    Disability: "",
    Drug: "",
    Handicap: "",
    Impairment: "",
    operationDate1: "",
    operation2: "",
    operationDate2: "",
    visualAcuity: "",
    basicHearingTest: "",
    cervicalCancerScreeningDone: false,
    prostateCancerScreeningDone: false,
    hivAidsScreeningDone: false,
    developmentalAndMentalEvaluation: "",
    expandedNewbornScreening: false,
    CBC2: false,
    bloodType: false,
    bloodTypeSpecify: "",
    FBS: false,
    sputumMicroscopy: false,
    slitSkinSmear: false,
    totalCholesterol: false,
    hdlCholesterol: false,
    serumandBun: false,
    routineUrinalysis: false,
    katoKatz: false,
    rapidPlasma: false,
    igmAndIgG: false,
    nonStructure: false,
    hepaB: false,
    fecalysis: false,
    malarialSmear: false,
    nucleicAndAmplification: false,
    allergyDrugsBl: false,
    DisabilityBl: false,
    DrugBl: false,
    HandicapBl: false,
    ImpairmentBl: false,
    allergy: false,
    smoking: "",
    number_of_sticks: 0,
    alcohol: "",
    number_of_bottles: 0,
    illicit_drugs: "",
    no_of_packs: "",
    skinPallor: false,
    skinRashes: false,
    skinJaundice: false,
    skinGoodSkinTurgor: false,
    heentAnicteric: false,
    heentIntactTympanic: false,
    heentExudates: false,
    heentPupils: false,
    heentTonsil: false,
    heentAuralDischarge: false,
    heentNasalDischarge: false,
    heentPalpableMass: false,
    chestSymmetrical: false,
    chestClearBreath: false,
    chestRetractions: false,
    chestCrackles: false,
    chestWheeze: false,
    heartAdynamic: false,
    heartMurmurs: false,
    heartNormalRate: false,
    heartHeaves: false,
    abdomenFlat: false,
    abdomenGlobular: false,
    abdomenFlabby: false,
    abdomenMuscleGuarding: false,
    abdomenTenderness: false,
    abdomenPalpableMass: false,
    extremetiesGrossDeformity: false,
    extremetiesNormalGait: false,
    extremetiesFullEqualPulse: false,
    neurologicalNormal: false,
    neurologicalDevelopmental: false,
    neurologicalSeizures: false,
    neurologicalMotorDeficit: false,
    neurologicalSensoryDeficit: false,
    diagnosis: "",
    treatment: "",
    healthcareProvider: "",
    administeredBy: ""
});
