import { MedicalAssessmentModel } from "./MedicalAssessment";

export interface MaternalModel {
    maternal_id?: number,
    user_id?: number,
    appointment_id?: string;
    firstname?: string;
    lastname?: string;
    birthdate?: string;
    age?: number;
    address?: string;
    education?: string;
    occupation?: string;
    husbandName?: string;
    husbandbirthdate?: string;
    husbandage?: number;
    dateofmarriage?: string;
    religion?: string;
    dateAdmitted?: string;
    dateDischarge?: string
    pastPTB?: boolean;
    pastHeartDisease?: boolean;
    pastDiabetes?: boolean;
    pastAsthma?: boolean;
    pastGoiter?: boolean;
    familyHistoryPTB?: boolean;
    familyHistoryHeartDisease?: boolean;
    familyHistoryDiabetes?: boolean;
    familyHistoryHypertension?: boolean;
    familyHistoryGoiter?: boolean;
    LMP?: string;
    EDC?: string;
    GRAVIDA?: string;
    PARA?: string;
    OBScore?: string;
    below18ORabove35?: boolean;
    pregnancyMore4?: boolean;
    poorObstetrical?: boolean;
    Below2YearsBirthInterval?: boolean;
    lessThan145cm?: boolean;
    moreThan145cm?: boolean;
    antePostPartrum?: boolean;
    prematureLabor?: boolean;
    abnormalPresentation?: boolean;
    preEnclampsia?: boolean;
    STD?: boolean;
    TT1?: boolean;
    TT2?: boolean;
    TT3?: boolean;
    TT4?: boolean;
    TT5?: boolean;
    medicalAssessment?: MedicalAssessmentModel[];
}